// app/pages/pia/index.vue
<script setup lang="ts">
const categories = [
  { title: "Product Innovation", desc: "Produk keuangan baru atau peningkatan fitur yang sudah ada." },
  { title: "Process Innovation", desc: "Optimasi alur kerja internal untuk efisiensi yang lebih tinggi." },
  { title: "Business Model", desc: "Strategi baru dalam menghasilkan nilai bagi Pegadaian." }
]

const timeline = [
  { date: "1 Mei - 31 Mei", title: "Submission Phase", desc: "Kirim ide inovasimu melalui portal PIA." },
  { date: "15 Juni", title: "Shortlisting", desc: "Seleksi administrasi dan scoring AI awal." },
  { date: "1 Juli", title: "Pitching Day", desc: "Presentasi di depan dewan juri ahli." },
  { date: "17 Agustus", title: "Awarding Night", desc: "Pengumuman pemenang di hari kemerdekaan." }
]
</script>

<template>
  <div class="pt-24 pb-32">
    <!-- PIA Hero -->
    <section class="py-24 px-6 relative overflow-hidden">
      <div class="absolute inset-0 bg-gradient-to-b from-gray-50/50 to-white"></div>
      <div class="container mx-auto max-w-5xl text-center relative z-10">
        <div class="inline-flex items-center gap-2 px-4 py-2 bg-yellow-50 text-yellow-700 rounded-full text-xs font-bold mb-8 mx-auto">
          <Icon name="heroicons:star-solid" class="w-4 h-4" />
          Pegadaian Innovation Awards 2026
        </div>
        <h1 class="text-6xl md:text-8xl font-black text-[#003366] leading-none mb-10">
          Saatnya <span class="bg-gradient-to-r from-[#D4AF37] to-yellow-600 bg-clip-text text-transparent">Bercahaya.</span>
        </h1>
        <p class="text-xl text-gray-500 max-w-2xl mx-auto leading-relaxed mb-12">
          Ajang kompetisi inovasi tahunan terbesar bagi seluruh karyawan Pegadaian. Raih total hadiah puluhan juta rupiah dan wujudkan idemu.
        </p>
        <NuxtLink to="/pia/submit" class="px-12 py-6 bg-[#003366] text-white rounded-3xl font-black text-xl shadow-2xl hover:scale-110 active:scale-95 transition-all outline outline-offset-8 outline-transparent hover:outline-[#003366]/20">
          Kirim Inovasi Sekarang
        </NuxtLink>
      </div>
    </section>

    <!-- Categories -->
    <section class="py-32">
      <div class="container mx-auto px-6">
        <h2 class="text-4xl font-bold text-[#003366] text-center mb-20">Kategori Penghargaan</h2>
        <div class="grid md:grid-cols-3 gap-10">
          <div v-for="c in categories" :key="c.title" class="p-10 bg-white rounded-[40px] border-2 border-gray-50 hover:border-[#D4AF37]/30 transition-all group">
            <div class="w-16 h-16 bg-[#003366] rounded-2xl mb-8 flex items-center justify-center group-hover:rotate-12 transition-transform">
              <Icon name="heroicons:trophy" class="w-8 h-8 text-white" />
            </div>
            <h3 class="text-2xl font-bold text-[#003366] mb-4">{{ c.title }}</h3>
            <p class="text-gray-500 leading-relaxed">{{ c.desc }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Timeline -->
    <section class="py-32 bg-gray-50/50">
      <div class="container mx-auto px-6 max-w-4xl">
        <h2 class="text-4xl font-bold text-[#003366] text-center mb-20">Timeline Kompetisi</h2>
        <div class="space-y-12">
          <div v-for="(step, i) in timeline" :key="i" class="flex gap-8 items-start">
            <div class="shrink-0 w-24 pt-1 font-bold text-[#D4AF37] text-sm uppercase tracking-widest text-right">
              {{ step.date }}
            </div>
            <div class="relative pt-1 pl-8 border-l-2 border-gray-200">
              <div class="absolute -left-[9px] top-1 w-4 h-4 rounded-full bg-white border-4 border-[#003366]"></div>
              <h3 class="text-2xl font-bold text-[#003366] mb-2">{{ step.title }}</h3>
              <p class="text-gray-500">{{ step.desc }}</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

// app/(public)/pia/page.tsx
import { MdCheckCircle, MdElectricBolt, MdSettings, MdSecurity } from "react-icons/md";

export default function PIAPage() {
  return (
    <div className="pt-12 pb-24 bg-white">
      {/* Hero Section */}
      <section className="container mx-auto px-6 max-w-5xl text-center mb-20">
        <div className="inline-block px-6 py-2 bg-yellow-50 text-pegadaian-green font-bold text-sm rounded-full mb-6 border border-yellow-200">
          🏆 Penghargaan Bergengsi
        </div>
        <h1 className="text-4xl md:text-6xl font-extrabold text-pegadaian-green tracking-tight leading-tight mb-6">
          Pegadaian Innovation Awards (PIA) 2026
        </h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
          Ajang apresiasi tertinggi bagi para inovator Pegadaian yang bertujuan mendorong budaya perbaikan berkesinambungan.
        </p>
      </section>

      <div className="container mx-auto px-6 max-w-5xl grid grid-cols-1 md:grid-cols-2 gap-16 items-start">
        {/* Kategori Penghargaan */}
        <div>
          <h2 className="text-3xl font-bold text-pegadaian-green mb-8">Kategori Penghargaan</h2>
          <div className="space-y-6">
            <div className="flex items-start gap-4 p-6 bg-gray-50 rounded-[12px] border border-gray-100 transition-all">
              <div className="w-14 h-14 bg-blue-100 text-blue-600 rounded-[12px] flex items-center justify-center shrink-0">
                <MdElectricBolt size={32} />
              </div>
              <div>
                <h3 className="text-xl font-bold text-pegadaian-green mb-2">Teknologi</h3>
                <p className="text-gray-600">Inovasi berbasis IT, digitalisasi, atau otomatisasi yang meningkatkan efisiensi dan keamanan.</p>
              </div>
            </div>

            <div className="flex items-start gap-4 p-6 bg-gray-50 rounded-[12px] border border-gray-100 transition-all">
              <div className="w-14 h-14 bg-green-100 text-green-600 rounded-[12px] flex items-center justify-center shrink-0">
                <MdSecurity size={32} />
              </div>
              <div>
                <h3 className="text-xl font-bold text-pegadaian-green mb-2">Layanan & Produk</h3>
                <p className="text-gray-600">Terobosan yang langsung dirasakan oleh nasabah, meningkatkan kepuasan dan loyalitas.</p>
              </div>
            </div>

            <div className="flex items-start gap-4 p-6 bg-gray-50 rounded-[12px] border border-gray-100 transition-all">
              <div className="w-14 h-14 bg-yellow-100 text-yellow-600 rounded-[12px] flex items-center justify-center shrink-0">
                <MdSettings size={32} />
              </div>
              <div>
                <h3 className="text-xl font-bold text-pegadaian-green mb-2">Proses Bisnis</h3>
                <p className="text-gray-600">Perbaikan alur kerja internal, efisiensi waktu, atau penurunan biaya operasional secara sistematis.</p>
              </div>
            </div>
          </div>
        </div>

        {/* Timeline Pendaftaran */}
        <div className="bg-pegadaian-green text-white rounded-[12px] p-10 relative">
          <h2 className="text-2xl font-bold mb-10 text-pegadaian-yellow">Timeline Kegiatan</h2>
          
          <div className="relative pl-8 border-l-2 border-white/20 space-y-10">
            <div className="relative">
              <div className="absolute -left-[41px] top-1 w-5 h-5 bg-pegadaian-yellow rounded-full border-4 border-pegadaian-green" />
              <h3 className="text-xl font-bold mb-1">1. Pendaftaran & Submit Ide</h3>
              <p className="text-gray-300 text-sm">1 Mei - 30 Juni 2026</p>
            </div>

            <div className="relative">
              <div className="absolute -left-[41px] top-1 w-5 h-5 bg-white rounded-full border-4 border-pegadaian-green" />
              <h3 className="text-xl font-bold mb-1">2. Seleksi Tahap Awal</h3>
              <p className="text-gray-300 text-sm">Juli 2026</p>
            </div>

            <div className="relative">
              <div className="absolute -left-[41px] top-1 w-5 h-5 bg-white rounded-full border-4 border-pegadaian-green" />
              <h3 className="text-xl font-bold mb-1">3. Inkubasi & Pitching</h3>
              <p className="text-gray-300 text-sm">Agustus - September 2026</p>
            </div>

            <div className="relative">
              <div className="absolute -left-[41px] top-1 w-5 h-5 bg-white rounded-full border-4 border-pegadaian-green" />
              <h3 className="text-xl font-bold mb-1">4. Malam Penganugerahan</h3>
              <p className="text-gray-300 text-sm">Bulan Inklusi Keuangan (Oktober 2026)</p>
            </div>
          </div>

          <a href="/pia/submit" className="block w-full text-center mt-12 py-4 bg-pegadaian-yellow text-pegadaian-green font-bold rounded-[6px] hover:opacity-90 transition-colors">
            Daftar Sekarang
          </a>
        </div>
      </div>
    </div>
  );
}
