// app/components/Navbar.vue
<script setup lang="ts">
const user = useSupabaseUser()
const supabase = useSupabaseClient()
const isMenuOpen = ref(false)
const profile = ref<any>(null)

// Fetch profile to get role
watchEffect(async () => {
  if (user.value) {
    const { data } = await supabase.from('profiles').select('*').eq('id', user.value.id).single()
    profile.value = data
  } else {
    profile.value = null
  }
})

const handleLogout = async () => {
  await supabase.auth.signOut()
  navigateTo('/login')
}

const role = computed(() => profile.value?.role || 'guest')
</script>

<template>
  <nav class="fixed top-0 w-full z-50 bg-white/80 backdrop-blur-md border-b">
    <div class="container mx-auto px-6 py-4 flex justify-between items-center">
      <!-- Logo -->
      <NuxtLink to="/" class="flex items-center gap-3">
        <img src="/logo.png" alt="Logo" class="h-10 w-auto object-contain" />
      </NuxtLink>

      <!-- Menus -->
      <div class="hidden md:flex gap-8 items-center text-sm font-semibold text-[#003366]">
        <NuxtLink to="/" class="hover:text-[#D4AF37] transition-colors">Beranda</NuxtLink>
        <NuxtLink to="/pia" class="hover:text-[#D4AF37] transition-colors">PIA</NuxtLink>
        
        <!-- Role Restricted Menus -->
        <template v-if="role !== 'guest'">
          <NuxtLink to="/idea-repository" class="hover:text-[#D4AF37] transition-colors">Idea Repository</NuxtLink>
          <NuxtLink to="/innovations" class="hover:text-[#D4AF37] transition-colors">Innovations</NuxtLink>
        </template>
        
        <NuxtLink to="/about" class="hover:text-[#D4AF37] transition-colors">About Us</NuxtLink>
        
        <!-- Admin/Superadmin specific -->
        <NuxtLink v-if="role === 'admin' || role === 'superadmin'" to="/admin" class="px-3 py-1 bg-red-50 text-red-600 rounded-lg text-xs font-bold uppercase tracking-wider">
          Admin Area
        </NuxtLink>
      </div>

      <!-- User Profile Access Section -->
      <div class="flex items-center gap-4 relative">
        <!-- 1. State: Logged In & Profile Loaded -->
        <div v-if="user && profile" class="relative">
          <button @click="isMenuOpen = !isMenuOpen" class="flex items-center gap-2 hover:bg-gray-50 p-2 rounded-xl transition-all">
            <div class="w-8 h-8 rounded-full bg-irish-green text-white flex items-center justify-center text-xs font-bold shadow-sm">
              {{ profile.full_name?.charAt(0) || 'U' }}
            </div>
            <Icon name="heroicons:chevron-down" class="w-4 h-4 text-gray-400 transition-transform" :class="{ 'rotate-180': isMenuOpen }" />
          </button>

          <!-- Dropdown -->
          <Transition
            enter-active-class="transition duration-100 ease-out"
            enter-from-class="transform scale-95 opacity-0"
            enter-to-class="transform scale-100 opacity-100"
            leave-active-class="transition duration-75 ease-in"
            leave-from-class="transform scale-100 opacity-100"
            leave-to-class="transform scale-95 opacity-0"
          >
            <div v-if="isMenuOpen" class="absolute right-0 mt-2 w-64 bg-white rounded-2xl shadow-xl border p-4 z-[100]">
              <div class="mb-4 pb-4 border-b">
                <div class="font-bold text-[#003366]">{{ profile.full_name }}</div>
                <div class="text-[10px] bg-blue-50 text-[#003366] px-2 py-0.5 rounded-full inline-block mt-1 font-bold uppercase tracking-wider">{{ role }}</div>
                <div class="text-xs text-gray-500 mt-2 truncate">{{ profile.email }}</div>
              </div>
              <div class="flex flex-col gap-2">
                <NuxtLink to="/user-settings" @click="isMenuOpen = false" class="flex items-center gap-2 p-2 hover:bg-gray-50 rounded-lg text-sm text-gray-700">
                  <Icon name="heroicons:cog-6-tooth" class="w-4 h-4" />
                  Pengaturan User
                </NuxtLink>
                <button @click="handleLogout" class="flex items-center gap-2 p-2 hover:bg-red-50 rounded-lg text-sm text-red-600 w-full text-left font-semibold">
                  <Icon name="heroicons:arrow-left-on-rectangle" class="w-4 h-4" />
                  Logout
                </button>
              </div>
            </div>
          </Transition>
        </div>

        <!-- 2. State: Logged In but Profile Loading -->
        <div v-else-if="user && !profile" class="flex items-center animate-pulse gap-2">
          <div class="w-8 h-8 rounded-full bg-gray-200"></div>
          <div class="h-4 w-12 bg-gray-100 rounded"></div>
        </div>

        <!-- 3. State: Not Logged In -->
        <NuxtLink v-else to="/login" class="btn-primary btn-sm">
          Login
        </NuxtLink>
      </div>
    </div>
  </nav>
</template>

// components/Navbar.tsx
'use client';

import { useState, useEffect } from 'react';
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';
import { useRouter } from 'next/navigation';
import { MdNotifications, MdAccountCircle, MdLogout, MdKeyboardArrowDown } from 'react-icons/md';
import Image from 'next/image';

export default function Navbar() {
  const [session, setSession] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [profileOpen, setProfileOpen] = useState(false);
  const supabase = createClientComponentClient();
  const router = useRouter();

  useEffect(() => {
    // Get initial session
    const getSession = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      setSession(session);
      setLoading(false);
    };
    
    getSession();

    // Listen for auth changes
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
    });

    return () => subscription.unsubscribe();
  }, [supabase]);

  const handleSignOut = async () => {
    await supabase.auth.signOut();
    setProfileOpen(false);
    router.push('/login');
    router.refresh();
  };

  return (
    <header className="bg-white border-b border-gray-100 sticky top-0 z-50 pegadaian-shadow">
      <div className="container mx-auto px-6 h-20 flex items-center justify-between">
        <a href="/" className="flex items-center gap-3 group hover:opacity-90 transition-opacity">
          {/* Logo updated to point to the user's provided logo image */}
          {/* We use standard img to avoid Next.js Image caching complexities if they swap the file frequently, but feel free to change to next/image later */}
          <img 
            src="/logo.png" 
            alt="Pegadaian Innovation Center" 
            className="h-[48px] w-auto object-contain"
            onError={(e) => {
              // Fallback visual if logo.png is not yet placed by the user
              e.currentTarget.style.display = 'none';
              const fallback = document.getElementById('logo-fallback');
              if (fallback) fallback.style.display = 'flex';
            }}
          />
          {/* Fallback that looks like the old logo inline SVG, just in case they haven't saved logo.png yet */}
          <div id="logo-fallback" className="hidden items-center gap-3" style={{ display: 'none' }}>
            <svg width="48" height="48" viewBox="0 0 48 48" fill="none" className="shrink-0">
              <path d="M 8 28 A 16 16 0 1 1 40 28" stroke="#7a8599" strokeWidth="4.5" strokeLinecap="round" />
              <path d="M 24 4 Q 24 18 36 18 Q 24 18 24 28 L 24 48 Q 24 18 12 18 Q 24 18 24 4 Z" fill="#f7c02b" />
            </svg>
            <div className="flex flex-col justify-center -space-y-1 mt-1">
              <span className="font-extrabold text-[22px] text-[#7a8599] leading-none tracking-tight lowercase">innovation</span>
              <span className="font-extrabold text-[22px] text-[#f7c02b] leading-none tracking-tight lowercase">center</span>
            </div>
          </div>
        </a>
        <nav className="hidden md:flex gap-8 text-sm font-medium text-gray-600">
          <a href="/" className="hover:text-pegadaian-green transition-colors">Beranda</a>
          <a href="/pia" className="hover:text-pegadaian-green transition-colors">PIA</a>
          <a href="/repository" className="hover:text-pegadaian-green transition-colors">Repository</a>
          <a href="/about" className="hover:text-pegadaian-green transition-colors">Tentang Kami</a>
          <a href="/contact" className="hover:text-pegadaian-green transition-colors">Kontak</a>
        </nav>
        
        <div className="flex items-center gap-2 md:gap-4 lg:gap-6">
          {!loading && !session ? (
            // Unauthenticated UI
            <div className="flex items-center gap-2 md:gap-4">
              <a href="/login" className="px-4 py-2 md:px-6 md:py-2 text-sm font-semibold text-pegadaian-green border border-pegadaian-green rounded-xl hover:bg-green-50 transition-colors">
                Login
              </a>
              <a href="/pia/submit" className="hidden sm:inline-flex px-4 py-2 md:px-6 md:py-2 text-sm font-semibold bg-pegadaian-green text-white rounded-xl hover:opacity-90 transition-all shadow-md hover:shadow-lg">
                Kirim Inovasi
              </a>
            </div>
          ) : !loading && session ? (
            // Authenticated UI
            <div className="flex items-center gap-2 sm:gap-4 relative">
              <a href="/pia/submit" className="hidden sm:inline-flex px-4 py-2 text-sm font-semibold bg-pegadaian-green text-white rounded-xl hover:opacity-90 transition-all shadow-sm">
                Kirim Inovasi
              </a>
              
              <button className="p-2 text-gray-500 hover:text-pegadaian-green hover:bg-green-50 rounded-full transition-colors relative">
                <MdNotifications size={24} />
                <span className="absolute top-2 right-2 w-2 h-2 bg-pegadaian-yellow rounded-full border border-white"></span>
              </button>

              <div className="relative">
                <button 
                  onClick={() => setProfileOpen(!profileOpen)}
                  onBlur={() => setTimeout(() => setProfileOpen(false), 200)}
                  className="flex items-center gap-2 p-2 hover:bg-gray-50 rounded-full sm:rounded-xl border border-transparent hover:border-gray-100 transition-all cursor-pointer"
                >
                  <MdAccountCircle size={28} className="text-gray-400" />
                  <span className="hidden w-16 sm:w-auto sm:block text-sm font-medium text-gray-700 max-w-[120px] truncate">
                    {session.user.user_metadata?.full_name || 'Profile'}
                  </span>
                  <MdKeyboardArrowDown size={20} className="text-gray-400 hidden sm:block" />
                </button>

                {profileOpen && (
                  <div className="absolute right-0 mt-2 w-56 bg-white rounded-xl pegadaian-shadow border border-gray-100 py-2 z-50">
                    <div className="px-4 py-2 border-b border-gray-50 mb-1">
                      <p className="text-sm font-semibold text-gray-800 truncate">
                        {session.user.user_metadata?.full_name || 'My Profile'}
                      </p>
                      <p className="text-xs text-gray-500 truncate">{session.user.email}</p>
                      <div className="mt-1 flex">
                        <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-50 text-blue-700 capitalize">
                          {session.user.user_metadata?.role || 'Peserta'}
                        </span>
                      </div>
                    </div>
                    {session.user.user_metadata?.role === 'superadmin' || session.user.user_metadata?.role === 'admin' ? (
                      <a href="/dashboard" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors">
                        Admin Dashboard
                      </a>
                    ) : null}
                    <a href="/profile" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors">
                      Pengaturan Profil
                    </a>
                    <button 
                      onMouseDown={(e) => { e.preventDefault(); handleSignOut(); }}
                      className="w-full text-left flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50 hover:text-red-700 transition-colors mt-1 border-t border-gray-50 pt-2"
                    >
                      <MdLogout size={20} />
                      Keluar
                    </button>
                  </div>
                )}
              </div>
            </div>
          ) : (
            // Loading skeleton or empty state
            <div className="w-32 h-10 bg-gray-100 animate-pulse rounded-xl"></div>
          )}
        </div>
      </div>
    </header>
  );
}
