// nuxt-app/app/components/InnovationCard.vue
<script setup lang="ts">
defineProps<{
  title: string
  category: string
  team: string
  summary: string
}>()
</script>

<template>
  <div class="bg-white rounded-2xl p-7 border border-gray-100 shadow-sm hover:shadow-md transition-shadow flex flex-col group">
    <div class="flex items-center justify-between mb-5">
      <span class="px-3 py-1 bg-green-50 text-green-600 text-xs font-bold rounded-full uppercase tracking-wider">
        {{ category }}
      </span>
      <div class="text-gray-300 group-hover:text-[#D4AF37] transition-colors">
        <Icon name="material-symbols:bookmark-outline" size="20" />
      </div>
    </div>
    <h3 class="text-xl font-bold text-[#003366] mb-3 leading-tight group-hover:text-[#D4AF37] transition-colors">
      {{ title }}
    </h3>
    <p class="text-gray-500 text-sm leading-relaxed mb-6 flex-grow">
      {{ summary }}
    </p>
    <div class="pt-5 border-t border-gray-50 flex items-center gap-3">
      <div class="w-8 h-8 rounded-full bg-blue-50 flex items-center justify-center shrink-0">
        <Icon name="material-symbols:person" class="text-blue-500" size="16" />
      </div>
      <div class="text-xs">
        <div class="text-gray-400">Tim</div>
        <div class="font-bold text-gray-700">{{ team }}</div>
      </div>
    </div>
  </div>
</template>

// components/ui/InnovationCard.tsx
'use client';
import { motion } from 'framer-motion';

export default function InnovationCard({ title = "Untitled", category = "Kategori", team = "Team", summary = "" }: any) {
  return (
    <div 
      className="bg-white rounded-2xl overflow-hidden border border-gray-100 transition-all cursor-pointer flex flex-col h-full group"
    >
      <div className="p-2">
        <div className="h-40 bg-gradient-to-br from-gray-50 to-gray-100 rounded-xl flex items-center justify-center relative overflow-hidden">
           <div className="absolute top-4 left-4 bg-pegadaian-yellow text-pegadaian-green text-[11px] uppercase tracking-wider font-bold px-4 py-2 rounded-full z-10">
             {category}
           </div>
           {/* Placeholder Icon */}
           <div className="w-16 h-16 rounded-full bg-white opacity-50 flex items-center justify-center">
             P
           </div>
        </div>
      </div>
      <div className="p-6 flex-grow flex flex-col">
        <h3 className="text-lg font-bold text-pegadaian-green mb-2 line-clamp-2 group-hover:text-pegadaian-yellow transition-colors leading-tight">{title}</h3>
        <p className="text-xs text-gray-500 font-medium mb-4 flex items-center gap-2 uppercase tracking-wider">
          <span className="inline-block w-2 h-2 rounded-full bg-blue-400"></span>
          {team}
        </p>
        <p className="text-gray-600 text-sm line-clamp-3 mb-6 flex-grow leading-relaxed">
          {summary}
        </p>
        <div className="mt-auto pt-4 border-t border-gray-50">
          <button className="text-pegadaian-green text-sm font-semibold flex items-center gap-2 group-hover:gap-4 transition-all group-hover:text-pegadaian-yellow">
            Pelajari Detail <span aria-hidden="true">→</span>
          </button>
        </div>
      </div>
    </div>
  );
}
