// nuxt-app/app/components/SearchFilterBar.vue
<template>
  <div class="flex flex-col md:flex-row gap-4 items-center w-full">
    <div class="relative flex-grow w-full">
      <div class="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-gray-400">
        <Icon name="material-symbols:search" size="20" />
      </div>
      <input 
        type="text" 
        placeholder="Cari inovasi (misal: AI, Blockchain...)" 
        class="w-full pl-12 pr-4 py-3.5 rounded-xl bg-white border border-gray-200 focus:outline-none focus:ring-2 focus:ring-[#D4AF37] shadow-sm transition-all"
      />
    </div>
    
    <div class="flex gap-2 w-full md:w-auto">
      <div class="relative w-full md:w-48">
        <select class="w-full pl-4 pr-10 py-3.5 rounded-xl bg-white border border-gray-200 focus:outline-none focus:ring-2 focus:ring-[#D4AF37] appearance-none shadow-sm font-medium text-gray-700">
          <option value="">Semua Kategori</option>
          <option value="teknologi">Teknologi</option>
          <option value="layanan">Layanan</option>
          <option value="prosess">Proses Bisnis</option>
        </select>
        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-4 text-gray-400">
          <Icon name="material-symbols:keyboard-arrow-down-rounded" />
        </div>
      </div>
    </div>
  </div>
</template>

// components/ui/SearchFilterBar.tsx
'use client';
import { useState } from 'react';
import { MdKeyboardArrowDown } from 'react-icons/md';

export default function SearchFilterBar({ onSearch }: { onSearch?: (val: string, cat: string) => void }) {
  const [term, setTerm] = useState('');
  const [category, setCategory] = useState('');

  const handleSearch = () => {
    if(onSearch) onSearch(term, category);
  };

  return (
    <div className="flex flex-col md:flex-row gap-4 bg-white p-4 rounded-[12px] pegadaian-shadow border border-gray-100 items-center">
      <input 
        type="text" 
        placeholder="Cari inovasi (cth: Layanan Gadai Digital)..." 
        className="flex-grow px-6 py-4 rounded-[6px] bg-gray-50 border border-gray-100 focus:outline-none focus:ring-2 focus:ring-pegadaian-yellow focus:bg-white transition-all w-full text-gray-800 placeholder-gray-400"
        value={term} onChange={(e) => setTerm(e.target.value)}
      />
      <div className="relative w-full md:w-64 shrink-0">
        <select 
          className="w-full py-4 pl-4 pr-12 rounded-[6px] bg-gray-50 border border-gray-100 focus:outline-none focus:ring-2 focus:ring-pegadaian-yellow transition-all text-gray-700 cursor-pointer appearance-none"
          value={category} onChange={(e) => setCategory(e.target.value)}
        >
          <option value="">Semua Kategori</option>
          <option value="teknologi">Teknologi</option>
          <option value="layanan">Layanan</option>
          <option value="proses-bisnis">Proses Bisnis</option>
        </select>
        <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-4 text-gray-500">
          <MdKeyboardArrowDown size={24} />
        </div>
      </div>
      <button 
        onClick={handleSearch}
        className="w-full md:w-auto px-8 py-4 bg-pegadaian-green hover:opacity-90 text-white font-semibold rounded-[6px] shadow-md hover:shadow-xl transition-all duration-300 active:scale-95 whitespace-nowrap shrink-0"
      >
        Cari Ide
      </button>
    </div>
  );
}
